version: '2'
linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wsl
    - testpackage
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - commentedOutCode
      settings:
        unnamedResult:
          checkExported: true
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
